language: node_js
node_js:
  - '12.16.0'
scripts:
  - yarn build:storybook
deploy:
  provider: pages
  local_dir: 'docs'
  github_token: $GITHUB_TOKEN
  keep_history: true
  cleanup: false
  skip_cleanup: true
  on:
    branch: master
branches:
  only:
    - master
